name: CI/CD workflow 

on:
  push:
    branches: 
      - main
  
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  cd: 
    needs: [ci]
    uses: ./.github/workflows/cd.yml
    secrets: inherit